apiVersion: v1
kind: ConfigMap
metadata:
  name: usersapi-config
data:
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"
  Jwt__Issuer: "FCG.UsersAPI"
  Jwt__Audience: "FCG"
  Jwt__ExpirationMinutes: "60"
