apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secret
type: Opaque
stringData:
  ConnectionStrings__Default: "Server=sqlserver;Database=FCG_UsersDB;User Id=sa;Password=Fcg@Sql2024!;TrustServerCertificate=True"
  Jwt__Secret: "super-secret-key-fcg-users-api-2024-min-32-chars!!"
  RabbitMQ__Password: "guest"
